version: '3.5'

services:
  postgres:
    image: postgres:13
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  adminer:
    image: adminer
    ports:
    - 9000:8080