"""Initital

Revision ID: 23ba16fe59ed
Revises: 
Create Date: 2021-02-15 02:13:42.535193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ba16fe59ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('minPriceIncrement', sa.Integer(), nullable=True),
    sa.Column('lot', sa.Integer(), nullable=True),
    sa.Column('minQuantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('figi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument')
    # ### end Alembic commands ###
